/**
 * 中国省份详细数据
 * 包含：省会、人口、面积、GDP、特色美食、著名景点、简介等
 */

const provinceData = {
    '北京': {
        pinyin: 'Běijīng',
        adminLevel: '直辖市',
        capital: '北京',
        population: 2189.3,
        area: 16410,
        gdp: 41610.9,
        gdpPerCapita: 190082,
        cuisine: '北京烤鸭、炸酱面、涮羊肉、豆汁儿、卤煮火烧',
        attractions: '故宫、长城、天坛、颐和园、圆明园、南锣鼓巷',
        description: '中华人民共和国首都，全国政治、文化、国际交往和科技创新中心，拥有3000多年历史，是世界著名的历史文化名城。'
    },
    '天津': {
        pinyin: 'Tiānjīn',
        adminLevel: '直辖市',
        capital: '天津',
        population: 1373.0,
        area: 11966,
        gdp: 16311.3,
        gdpPerCapita: 118806,
        cuisine: '狗不理包子、耳朵眼炸糕、十八街麻花、煎饼果子',
        attractions: '五大道、天津之眼、古文化街、瓷房子、意式风情区',
        description: '中国北方最大的港口城市，环渤海经济圈的重要城市，近代工业发源地，具有独特的中西合璧城市风貌。'
    },
    '河北': {
        pinyin: 'Héběi',
        adminLevel: '省',
        capital: '石家庄',
        population: 7448.0,
        area: 188800,
        gdp: 42370.4,
        gdpPerCapita: 56883,
        cuisine: '驴肉火烧、正定八大碗、保定酱菜、承德烤全羊',
        attractions: '承德避暑山庄、山海关、北戴河、白洋淀、野三坡',
        description: '华北地区重要省份，环抱首都北京，是中华民族的发祥地之一，拥有世界文化遗产——承德避暑山庄及周围寺庙。'
    },
    '山西': {
        pinyin: 'Shānxī',
        adminLevel: '省',
        capital: '太原',
        population: 3480.5,
        area: 156700,
        gdp: 25642.6,
        gdpPerCapita: 73680,
        cuisine: '刀削面、平遥牛肉、太谷饼、莜面栲栳栳、羊杂割',
        attractions: '平遥古城、云冈石窟、五台山、悬空寺、乔家大院',
        description: '中华文明重要发祥地，被誉为"华夏文明摇篮"，拥有3处世界文化遗产，是中国古建筑保存最完好的省份。'
    },
    '内蒙古': {
        pinyin: 'Nèi Měnggǔ',
        adminLevel: '自治区',
        capital: '呼和浩特',
        population: 2400.0,
        area: 1183000,
        gdp: 23158.6,
        gdpPerCapita: 96494,
        cuisine: '烤全羊、手把肉、奶茶、莜面、羊肉烧麦',
        attractions: '呼伦贝尔草原、响沙湾、阿尔山、额济纳胡杨林',
        description: '中国第三大省级行政区，横跨东北、华北、西北三大地区，是中国最重要的畜牧业基地，草原风光壮美。'
    },
    '辽宁': {
        pinyin: 'Liáoníng',
        adminLevel: '省',
        capital: '沈阳',
        population: 4229.0,
        area: 148000,
        gdp: 28975.1,
        gdpPerCapita: 68497,
        cuisine: '锅包肉、老边饺子、沈阳鸡架、大连海鲜',
        attractions: '沈阳故宫、大连金石滩、千山、本溪水洞、红海滩',
        description: '东北地区唯一沿海省份，中国重工业基地，清朝发祥地，拥有沈阳故宫等世界文化遗产。'
    },
    '吉林': {
        pinyin: 'Jílín',
        adminLevel: '省',
        capital: '长春',
        population: 2375.4,
        area: 187400,
        gdp: 13236.4,
        gdpPerCapita: 55729,
        cuisine: '延边冷面、白肉血肠、锅包肉、人参炖鸡',
        attractions: '长白山、净月潭、伪满皇宫、松花湖、雾凇岛',
        description: '中国东北中部省份，拥有世界著名的长白山自然保护区，是中国重要的商品粮基地和汽车工业基地。'
    },
    '黑龙江': {
        pinyin: 'Hēilóngjiāng',
        adminLevel: '省',
        capital: '哈尔滨',
        population: 3099.0,
        area: 473000,
        gdp: 15901.0,
        gdpPerCapita: 51310,
        cuisine: '锅包肉、哈尔滨红肠、得莫利炖鱼、杀猪菜',
        attractions: '哈尔滨冰雪大世界、中央大街、镜泊湖、五大连池',
        description: '中国最北、最东的省份，冰雪旅游胜地，拥有亚洲最大的湿地——扎龙自然保护区，是重要的商品粮基地。'
    },
    '上海': {
        pinyin: 'Shànghǎi',
        adminLevel: '直辖市',
        capital: '上海',
        population: 2489.4,
        area: 6340,
        gdp: 47218.7,
        gdpPerCapita: 189623,
        cuisine: '小笼包、生煎、红烧肉、糖醋排骨、本帮菜',
        attractions: '外滩、东方明珠、迪士尼、豫园、南京路',
        description: '中国最大的经济中心城市，国际金融、贸易、航运中心，现代化国际大都市，东西方文化交融的典范城市。'
    },
    '江苏': {
        pinyin: 'Jiāngsū',
        adminLevel: '省',
        capital: '南京',
        population: 8505.4,
        area: 107200,
        gdp: 128222.2,
        gdpPerCapita: 150690,
        cuisine: '南京盐水鸭、苏州松鼠桂鱼、无锡排骨、扬州炒饭',
        attractions: '苏州园林、南京中山陵、扬州瘦西湖、周庄古镇',
        description: '中国经济最发达的省份之一，拥有中国最古老的园林文化，是吴文化、楚汉文化的发祥地。'
    },
    '浙江': {
        pinyin: 'Zhèjiāng',
        adminLevel: '省',
        capital: '杭州',
        population: 6577.0,
        area: 105500,
        gdp: 77715.4,
        gdpPerCapita: 118174,
        cuisine: '杭州东坡肉、龙井虾仁、宁波汤圆、温州鱼丸',
        attractions: '西湖、乌镇、千岛湖、普陀山、雁荡山',
        description: '中国经济大省，民营经济最发达的省份，拥有世界文化遗产西湖，是江南水乡的典型代表。'
    },
    '安徽': {
        pinyin: 'Ānhuī',
        adminLevel: '省',
        capital: '合肥',
        population: 6127.0,
        area: 140100,
        gdp: 47050.6,
        gdpPerCapita: 76786,
        cuisine: '徽菜、臭鳜鱼、毛豆腐、符离集烧鸡、淮南牛肉汤',
        attractions: '黄山、宏村、西递、九华山、天柱山',
        description: '中国文化大省，徽文化发源地，拥有世界文化与自然遗产——黄山，是中国八大菜系之一徽菜的故乡。'
    },
    '福建': {
        pinyin: 'Fújiàn',
        adminLevel: '省',
        capital: '福州',
        population: 4188.0,
        area: 124000,
        gdp: 53109.9,
        gdpPerCapita: 126809,
        cuisine: '佛跳墙、沙茶面、土笋冻、福州鱼丸、厦门薄饼',
        attractions: '厦门鼓浪屿、武夷山、土楼、泉州、太姥山',
        description: '中国著名侨乡，海上丝绸之路起点，茶文化发源地，拥有独特的闽南文化和客家文化。'
    },
    '江西': {
        pinyin: 'Jiāngxī',
        adminLevel: '省',
        capital: '南昌',
        population: 4528.0,
        area: 166900,
        gdp: 32074.7,
        gdpPerCapita: 70837,
        cuisine: '瓦罐汤、南昌拌粉、藜蒿炒腊肉、庐山石鸡',
        attractions: '庐山、井冈山、滕王阁、三清山、婺源',
        description: '中国革命圣地，红色旅游重要目的地，拥有世界自然遗产三清山，是中国最美乡村婺源所在地。'
    },
    '山东': {
        pinyin: 'Shāndōng',
        adminLevel: '省',
        capital: '济南',
        population: 10152.7,
        area: 157900,
        gdp: 87435.1,
        gdpPerCapita: 86125,
        cuisine: '鲁菜、煎饼卷大葱、德州扒鸡、糖醋鲤鱼',
        attractions: '泰山、曲阜三孔、青岛栈桥、趵突泉、崂山',
        description: '中国人口第二大省，孔孟之乡，齐鲁文化发源地，拥有世界自然与文化遗产泰山。'
    },
    '河南': {
        pinyin: 'Hénán',
        adminLevel: '省',
        capital: '郑州',
        population: 9872.0,
        area: 167000,
        gdp: 61345.1,
        gdpPerCapita: 62129,
        cuisine: '烩面、胡辣汤、灌汤包、道口烧鸡、洛阳水席',
        attractions: '少林寺、龙门石窟、清明上河园、白马寺、云台山',
        description: '中华文明核心发源地，中国古都最多的省份，拥有洛阳龙门石窟等5处世界文化遗产。'
    },
    '湖北': {
        pinyin: 'Húběi',
        adminLevel: '省',
        capital: '武汉',
        population: 5844.0,
        area: 185900,
        gdp: 55803.6,
        gdpPerCapita: 95477,
        cuisine: '热干面、武昌鱼、排骨藕汤、鸭脖、豆皮',
        attractions: '黄鹤楼、武当山、三峡大坝、神农架、东湖',
        description: '中国中部重要省份，九省通衢之地，拥有道教圣地武当山，是楚文化的发祥地。'
    },
    '湖南': {
        pinyin: 'Húnán',
        adminLevel: '省',
        capital: '长沙',
        population: 6622.0,
        area: 211800,
        gdp: 49706.6,
        gdpPerCapita: 75058,
        cuisine: '湘菜、剁椒鱼头、臭豆腐、毛氏红烧肉、口味虾',
        attractions: '张家界、凤凰古城、岳麓山、橘子洲、韶山',
        description: '中国文化大省，湖湘文化发源地，拥有世界自然遗产张家界，是中国革命的重要策源地。'
    },
    '广东': {
        pinyin: 'Guǎngdōng',
        adminLevel: '省',
        capital: '广州',
        population: 12684.0,
        area: 179700,
        gdp: 129118.6,
        gdpPerCapita: 101793,
        cuisine: '粤菜、早茶、烧鹅、肠粉、煲仔饭、白切鸡',
        attractions: '广州塔、深圳世界之窗、珠海长隆、开平碉楼',
        description: '中国第一经济大省，改革开放前沿阵地，粤港澳大湾区核心区域，中国最大的侨乡。'
    },
    '广西': {
        pinyin: 'Guǎngxī',
        adminLevel: '自治区',
        capital: '南宁',
        population: 5027.0,
        area: 237600,
        gdp: 26300.9,
        gdpPerCapita: 52330,
        cuisine: '桂林米粉、螺蛳粉、柠檬鸭、老友粉',
        attractions: '桂林山水、漓江、阳朔、北海银滩、德天瀑布',
        description: '中国著名的旅游大省，"桂林山水甲天下"，拥有绝美的喀斯特地貌，是壮族聚居区。'
    },
    '海南': {
        pinyin: 'Hǎinán',
        adminLevel: '省',
        capital: '海口',
        population: 1027.0,
        area: 35400,
        gdp: 7113.3,
        gdpPerCapita: 69269,
        cuisine: '文昌鸡、和乐蟹、东山羊、加积鸭、椰子饭',
        attractions: '三亚亚龙湾、蜈支洲岛、天涯海角、南山寺',
        description: '中国最南端的省份，国际旅游岛，中国最大的经济特区，拥有热带海滨风光和自贸港政策。'
    },
    '重庆': {
        pinyin: 'Chóngqìng',
        adminLevel: '直辖市',
        capital: '重庆',
        population: 3212.4,
        area: 82400,
        gdp: 29129.0,
        gdpPerCapita: 90665,
        cuisine: '重庆火锅、小面、酸辣粉、毛血旺、辣子鸡',
        attractions: '洪崖洞、解放碑、武隆天坑、长江三峡、大足石刻',
        description: '中国西部唯一直辖市，山城、雾都、火锅之都，拥有世界文化遗产大足石刻，是长江上游经济中心。'
    },
    '四川': {
        pinyin: 'Sìchuān',
        adminLevel: '省',
        capital: '成都',
        population: 8374.0,
        area: 486000,
        gdp: 56749.8,
        gdpPerCapita: 67775,
        cuisine: '川菜、麻婆豆腐、宫保鸡丁、回锅肉、担担面',
        attractions: '九寨沟、峨眉山、都江堰、青城山、大熊猫基地',
        description: '天府之国，中国西部经济强省，拥有世界自然遗产九寨沟和大熊猫栖息地，是川菜发源地。'
    },
    '贵州': {
        pinyin: 'Guìzhōu',
        adminLevel: '省',
        capital: '贵阳',
        population: 3856.0,
        area: 176100,
        gdp: 20956.0,
        gdpPerCapita: 54350,
        cuisine: '酸汤鱼、丝娃娃、肠旺面、贵州米粉',
        attractions: '黄果树瀑布、梵净山、荔波小七孔、西江千户苗寨',
        description: '中国西南部山地省份，多民族聚居地，拥有亚洲最大瀑布黄果树，是茅台酒的故乡。'
    },
    '云南': {
        pinyin: 'Yúnnán',
        adminLevel: '省',
        capital: '昆明',
        population: 4720.9,
        area: 394000,
        gdp: 28954.2,
        gdpPerCapita: 61332,
        cuisine: '过桥米线、汽锅鸡、宣威火腿、鲜花饼',
        attractions: '丽江古城、大理、昆明石林、西双版纳、玉龙雪山',
        description: '中国少数民族最多的省份，"彩云之南"，拥有三项世界遗产，是中国生物多样性最丰富的省份。'
    },
    '西藏': {
        pinyin: 'Xīzàng',
        adminLevel: '自治区',
        capital: '拉萨',
        population: 366.0,
        area: 1228400,
        gdp: 2132.6,
        gdpPerCapita: 58269,
        cuisine: '糌粑、酥油茶、青稞酒、藏式酸奶',
        attractions: '布达拉宫、纳木错、珠穆朗玛峰、大昭寺',
        description: '世界屋脊，地球第三极，拥有世界最高峰珠穆朗玛峰，是藏传佛教圣地，自然风光雄奇壮美。'
    },
    '陕西': {
        pinyin: 'Shǎnxī',
        adminLevel: '省',
        capital: '西安',
        population: 3954.0,
        area: 205600,
        gdp: 32772.7,
        gdpPerCapita: 82870,
        cuisine: '羊肉泡馍、肉夹馍、凉皮、臊子面、biangbiang面',
        attractions: '秦始皇兵马俑、华山、大雁塔、古城墙、华清池',
        description: '中华文明重要发祥地，十三朝古都所在地，拥有世界第八大奇迹秦始皇兵马俑。'
    },
    '甘肃': {
        pinyin: 'Gānsù',
        adminLevel: '省',
        capital: '兰州',
        population: 2490.0,
        area: 454000,
        gdp: 11399.3,
        gdpPerCapita: 45777,
        cuisine: '兰州拉面、酿皮子、手抓羊肉、灰豆子',
        attractions: '敦煌莫高窟、嘉峪关、鸣沙山月牙泉、张掖丹霞',
        description: '丝绸之路黄金段，拥有世界文化遗产莫高窟，是中国西部重要的交通枢纽。'
    },
    '青海': {
        pinyin: 'Qīnghǎi',
        adminLevel: '省',
        capital: '西宁',
        population: 595.0,
        area: 722300,
        gdp: 3579.9,
        gdpPerCapita: 60167,
        cuisine: '青海老酸奶、手抓羊肉、酥油糌粑、酿皮',
        attractions: '青海湖、塔尔寺、茶卡盐湖、可可西里',
        description: '中华水塔，长江、黄河、澜沧江的发源地，拥有中国最大的内陆咸水湖青海湖。'
    },
    '宁夏': {
        pinyin: 'Níngxià',
        adminLevel: '自治区',
        capital: '银川',
        population: 725.0,
        area: 66400,
        gdp: 5069.6,
        gdpPerCapita: 69925,
        cuisine: '手抓羊肉、羊肉臊子面、八宝茶、滩羊肉',
        attractions: '沙坡头、西夏王陵、沙湖、六盘山',
        description: '塞上江南，中国伊斯兰教重要聚居区，回族自治区，拥有独特的西夏文化遗产。'
    },
    '新疆': {
        pinyin: 'Xīnjiāng',
        adminLevel: '自治区',
        capital: '乌鲁木齐',
        population: 2587.0,
        area: 1664900,
        gdp: 18327.8,
        gdpPerCapita: 70847,
        cuisine: '大盘鸡、羊肉串、馕、烤全羊、拌面',
        attractions: '天山天池、喀纳斯、塔克拉玛干沙漠、那拉提草原',
        description: '中国面积最大的省级行政区，古丝绸之路重镇，多民族聚居区，拥有壮美的自然风光。'
    },
    '香港': {
        pinyin: 'Xiānggǎng',
        adminLevel: '特别行政区',
        capital: '香港',
        population: 733.5,
        area: 1106,
        gdp: 28191.0,
        gdpPerCapita: 384378,
        cuisine: '港式茶餐厅、烧腊、云吞面、菠萝包、鸳鸯奶茶',
        attractions: '维多利亚港、太平山、迪士尼、赤柱、海洋公园',
        description: '东方之珠，国际金融中心，购物天堂，中西文化交融的国际大都市。'
    },
    '澳门': {
        pinyin: 'Àomén',
        adminLevel: '特别行政区',
        capital: '澳门',
        population: 68.3,
        area: 32.9,
        gdp: 1804.0,
        gdpPerCapita: 264129,
        cuisine: '葡式蛋挞、猪扒包、水蟹粥、非洲鸡',
        attractions: '大三巴牌坊、威尼斯人、妈阁庙、澳门塔',
        description: '世界娱乐之都，中葡文化交融的历史名城，拥有澳门历史城区世界文化遗产。'
    },
    '台湾': {
        pinyin: 'Táiwān',
        adminLevel: '省',
        capital: '台北',
        population: 2342.0,
        area: 36193,
        gdp: 47000.0,
        gdpPerCapita: 200683,
        cuisine: '卤肉饭、珍珠奶茶、牛肉面、小笼包、蚵仔煎',
        attractions: '台北101、日月潭、阿里山、垦丁、九份',
        description: '宝岛台湾，中国第一大岛，拥有丰富的自然资源和独特的闽南文化，是中华文化的重要传承地。'
    },
    '南海诸岛': {
        pinyin: 'Nánhǎi Zhūdǎo',
        adminLevel: '群岛',
        capital: '三沙市',
        population: 2.5,
        area: 13,
        gdp: 25.0,
        gdpPerCapita: 100000,
        cuisine: '海鲜、椰子',
        attractions: '永兴岛、西沙群岛、南沙群岛',
        description: '中国南海最南端的岛礁群，战略位置重要，拥有丰富的海洋资源。'
    }
};

// 人口数据（用于地图着色）- 单位：万人
const populationData = [
    { name: '北京', value: 2189.3 },
    { name: '天津', value: 1373.0 },
    { name: '河北', value: 7448.0 },
    { name: '山西', value: 3480.5 },
    { name: '内蒙古', value: 2400.0 },
    { name: '辽宁', value: 4229.0 },
    { name: '吉林', value: 2375.4 },
    { name: '黑龙江', value: 3099.0 },
    { name: '上海', value: 2489.4 },
    { name: '江苏', value: 8505.4 },
    { name: '浙江', value: 6577.0 },
    { name: '安徽', value: 6127.0 },
    { name: '福建', value: 4188.0 },
    { name: '江西', value: 4528.0 },
    { name: '山东', value: 10152.7 },
    { name: '河南', value: 9872.0 },
    { name: '湖北', value: 5844.0 },
    { name: '湖南', value: 6622.0 },
    { name: '广东', value: 12684.0 },
    { name: '广西', value: 5027.0 },
    { name: '海南', value: 1027.0 },
    { name: '重庆', value: 3212.4 },
    { name: '四川', value: 8374.0 },
    { name: '贵州', value: 3856.0 },
    { name: '云南', value: 4720.9 },
    { name: '西藏', value: 366.0 },
    { name: '陕西', value: 3954.0 },
    { name: '甘肃', value: 2490.0 },
    { name: '青海', value: 595.0 },
    { name: '宁夏', value: 725.0 },
    { name: '新疆', value: 2587.0 },
    { name: '香港', value: 733.5 },
    { name: '澳门', value: 68.3 },
    { name: '台湾', value: 2342.0 }
];

// GDP数据 - 单位：亿元
const gdpData = [
    { name: '北京', value: 41610.9 },
    { name: '天津', value: 16311.3 },
    { name: '河北', value: 42370.4 },
    { name: '山西', value: 25642.6 },
    { name: '内蒙古', value: 23158.6 },
    { name: '辽宁', value: 28975.1 },
    { name: '吉林', value: 13236.4 },
    { name: '黑龙江', value: 15901.0 },
    { name: '上海', value: 47218.7 },
    { name: '江苏', value: 128222.2 },
    { name: '浙江', value: 77715.4 },
    { name: '安徽', value: 47050.6 },
    { name: '福建', value: 53109.9 },
    { name: '江西', value: 32074.7 },
    { name: '山东', value: 87435.1 },
    { name: '河南', value: 61345.1 },
    { name: '湖北', value: 55803.6 },
    { name: '湖南', value: 49706.6 },
    { name: '广东', value: 129118.6 },
    { name: '广西', value: 26300.9 },
    { name: '海南', value: 7113.3 },
    { name: '重庆', value: 29129.0 },
    { name: '四川', value: 56749.8 },
    { name: '贵州', value: 20956.0 },
    { name: '云南', value: 28954.2 },
    { name: '西藏', value: 2132.6 },
    { name: '陕西', value: 32772.7 },
    { name: '甘肃', value: 11399.3 },
    { name: '青海', value: 3579.9 },
    { name: '宁夏', value: 5069.6 },
    { name: '新疆', value: 18327.8 },
    { name: '香港', value: 28191.0 },
    { name: '澳门', value: 1804.0 },
    { name: '台湾', value: 47000.0 }
];

// 面积数据 - 单位：平方公里
const areaData = [
    { name: '北京', value: 16410 },
    { name: '天津', value: 11966 },
    { name: '河北', value: 188800 },
    { name: '山西', value: 156700 },
    { name: '内蒙古', value: 1183000 },
    { name: '辽宁', value: 148000 },
    { name: '吉林', value: 187400 },
    { name: '黑龙江', value: 473000 },
    { name: '上海', value: 6340 },
    { name: '江苏', value: 107200 },
    { name: '浙江', value: 105500 },
    { name: '安徽', value: 140100 },
    { name: '福建', value: 124000 },
    { name: '江西', value: 166900 },
    { name: '山东', value: 157900 },
    { name: '河南', value: 167000 },
    { name: '湖北', value: 185900 },
    { name: '湖南', value: 211800 },
    { name: '广东', value: 179700 },
    { name: '广西', value: 237600 },
    { name: '海南', value: 35400 },
    { name: '重庆', value: 82400 },
    { name: '四川', value: 486000 },
    { name: '贵州', value: 176100 },
    { name: '云南', value: 394000 },
    { name: '西藏', value: 1228400 },
    { name: '陕西', value: 205600 },
    { name: '甘肃', value: 454000 },
    { name: '青海', value: 722300 },
    { name: '宁夏', value: 66400 },
    { name: '新疆', value: 1664900 },
    { name: '香港', value: 1106 },
    { name: '澳门', value: 32.9 },
    { name: '台湾', value: 36193 }
];
